### ISSUE TITLE
Starting game from build on Windows machine fails in esbuild's issue with glob syntax

### ISSUE THREAD

**Issue by tronster** [piesku/duszki#2]
Love the game and what a treat the Typescript code is well organized and even commented in places.

Following the instructions in `README.md` on a Windows 10 machine with the latest (Stable) VSCode, after running npm start the output in the Terminal and when browsing to `http://localhost:1234` is:
```PS C:\projects\github\duszki> npm start```

> \`npm\` WARN config global \`--global\`, \`--local\` are deprecated. Use \`--location=global\` instead.
>
> \> goodluck@0.0.0 start
> \> esbuild */index.ts --define:DEBUG=true --target=es2020 --preserve-symlinks --bundle --sourcemap --outdir=. --outbase=. --color=false --servedir=. --serve=1234
> 
> \> Network: http://192.168.1.33:1234/
> \> Local:   http://127.0.0.1:1234/
> \> Network: http://172.25.208.1:1234/
>
> X [ERROR] Could not resolve "*/index.ts"
>
>  It looks like you are trying to use glob syntax (i.e. "*") with esbuild. This syntax is typically
>  handled by your shell, and isn't handled by esbuild itself. You must expand glob syntax first
>  before passing your paths to esbuild.
>
> 1 error

I'm assuming the glob has to do with wildcard star expansion.  Any ideas on what needs to be modified in the `package.json` or else-where to get this to build?

If the following lines are changed from starting with "*/index.ts" to "src/index.ts" the browser will start with an index directory, and the game can be run by clicking into "src".  (Partial fix).  The lines to change in `package.json`, "scripts" section:
> "start": "esbuild src/index.ts --define:DEBUG=true --target=es2020 --preserve-symlinks --bundle --sourcemap --outdir=. --outbase=. --color=false --servedir=. --serve=1234",
> "build": "esbuild scripts/index.ts --define:DEBUG=true --target=es2020 --preserve-symlinks --bundle --sourcemap --outdir=. --outbase=. --color=false",

**Comment by stasm** [comment]
Hi @tronster, thanks for the report! I'm happy to know that you're enjoying the game <3.

I've only ever tested our setup inside WSL on Windows, hence the use of a Bash-like `*` glob. As you note, changing `*/index.ts` to point directly to `src/index.ts` is the right fix.

Background: The `*` is there due to the fact that the repo was generated from our template, https://github.com/piesku/goodluck. The template has multiple examples, each one in its own directory and with its own `index.ts` entry point. Ideally, when a new project is bootstrapped from the template and all examples are removed, we'd automatically change `*/index.ts` to `src/index.ts`.
